version: v1.1

llm:
  provider: openai
  config:
    model: gpt-4o-mini
    temperature: 0.2
    max_tokens: 1500
    top_p: 1

embedder:
  provider: openai
  config:
    model: text-embedding-3-small

vector_store:
  provider: qdrant
  config:
    collection_name: mem0
    host: qdrant
    port: 6333
    embedding_model_dims: 1536

history_db:
  provider: sqlite
